# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
target 'RateMyLife' do
	pod "SwipeViewController"
    pod 'Alamofire', '~> 4.0'

    pod "CircleSlider"
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
	use_frameworks!
end
